### ISSUE TITLE
Can't backup ap-southeast-1 buckets

### ISSUE THREAD

**Issue by rstacruz** [myriadmobile/deis-backup-restore#1]
I'm getting this:

```
Traceback (most recent call last):
  File "./main.py", line 478, in <module>
    object.backup()
  File "./main.py", line 106, in backup
    self.backup_etcd()
  File "./main.py", line 276, in backup_etcd
    bucket = self.get_remote_s3_bucket()
  File "./main.py", line 95, in get_remote_s3_bucket
    return self.get_remote_s3_connection().get_bucket(self._remote_bucket_name)
  File "/env/lib/python2.7/site-packages/boto/s3/connection.py", line 502, in get_bucket
    return self.head_bucket(bucket_name, headers=headers)
  File "/env/lib/python2.7/site-packages/boto/s3/connection.py", line 549, in head_bucket
    response.status, response.reason, body)
boto.exception.S3ResponseError: S3ResponseError: 301 Moved Permanently
```

 Related: https://github.com/boto/boto/issues/443

**Comment by EvgenOleynikov** [comment]
same error
